dist: trusty

language: python
python:
  - 2.7
  - 3.5

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install tensorflow
  - pip install -r requirements.txt

script:
  # Tests
  - pytest

  # Synchronous algorithms
  - python main.py --summary_step_period 4 --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --boostrapped --game air_raid --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --dueling --game amidar --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --double_q --game assault --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --exploration_bonus --game asterix --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --optimality_tightening --game asteroids --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --persistent_advantage_learning --game atlantis --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --replay_priorities proportional --game BankHeist --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --reward_scaling --game battle_zone --replay_start_size 8 --num_steps 8 --initial_exploration 0.5
  - python main.py --sarsa --game beam_rider --replay_start_size 8 --num_steps 8 --initial_exploration 0.5

  # All synchronous algorithms combined
  - python main.py --boostrapped --dueling --double_q --exploration_bonus --optimality_tightening --persistent_advantage_learning --replay_prioritized --reward_scaling --game yars_revenge --replay_start_size 8 --num_steps 8 --initial_exploration 0.5

  # Asynchronous algorithms
  - python main.py --async one_step --game Berzerk --num_steps 8 --num_threads 4 --initial_exploration 0.5
  - python main.py --async n_step --game bowling --num_steps 8 --num_threads 4 --initial_exploration 0.5
  - python main.py --async n_step --sarsa --game boxing --num_steps 8 --num_threads 4 --initial_exploration 0.5
  - python main.py --async a3c --game Breakout --num_steps 8 --num_threads 4 --initial_exploration 0.5

notifications:
  email: false
  slack:
    rooms:
      secure: hXSpVdGwpVhJVa5jHj3NLPKLgVjKxF3nb4aBeuAPkCgpcPcBxKITD/BRXTPb5XQwE4Ccq7joihs/HlCVlio0+sSTMQIjxr1TNZcXS26Oz/lkY6O0ZRfB9rnftNas6Mea8dz6cUAnIcjaaXBzAn4N13tVj/vbsWWpbB9/2Xpjqk4ax1eL9KiD1KlJXLjoB6lXaMSbCm9bmURAJZf507ZaXz8pehW29RsOcnJyhjlmHB3i26rRVk2evHv4Y6PXZSOLxsMY7XV4PfqoJKznFBCTSB+WHtTfQLU35JnvHH3YMW9K+wAlQcoTzIMMGHwGyz7pJUM/s2uIgEy7wWdB0sF3bDg4NCPrx6KHv0up4c4ow89ElLfkEsx+wZUvXCcsGApLfnf6WZb6i3momKzB2xalond5xzqTvdmjB7K0U+dEdPq/M7R1PMZZSTYG0hee9ATWHvjK1QZmYPTM0T+J5GxgTckz4NUvX8owejUFZGdAQED7Q+vvODLMxnDckIx/pCq5Swcirjmo83tAPmopavKozDTjus/vjM21gvVvxJwgEDcMjfrub7Y6iqQoJ+gTDDeh3xEzZGnzWAX4ax9PI0oXequmacs8xqrGbMrUI0S0ZxTAWgjeQ7HalNIxmqosdDnDedI8dE5ruRmng4BK4zATh2X6NuWDfVRKh3sX27aAKFc=
    on_success: change
    on_failure: always
